name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.8"

      - name: Build
        run: |
          python -m pip install -U pip pep517 twine setuptools_scm
          python -m pep517.build .

      - name: Test the sdist
        run: |
          python -m venv venv-sdist
          venv-sdist/bin/python -m pip install dist/dominion*.tar.gz
          venv-sdist/bin/python -c "import dominion;print(dominion.__version__)"
          venv-sdist/bin/python -m dominion version
          venv-sdist/bin/dominion version
          venv-sdist/bin/dominion list sets

      - name: Test the wheel
        run: |
          python -m venv venv-wheel
          venv-wheel/bin/python -m pip install dist/dominion*.whl
          venv-wheel/bin/python -c "import dominion;print(dominion.__version__)"
          venv-wheel/bin/python -m dominion version
          venv-wheel/bin/dominion version
          venv-wheel/bin/dominion list sets

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*

  upload_pypi:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          # To test: repository_url: https://test.pypi.org/legacy/
